GLSLPROC = ./process-shaders

AUTOGEN_FILES = \
	autogenerated/shaders.h \
	autogenerated/shaders.c

GLSL_FILES = \
	glsl/line.vert \
	glsl/line.frag

C_FILES = \
	src/main.c \
	src/memory.c \
	src/gfx.c \
	src/glx11.c \
	src/window.c \
	src/logging.c \

OBJECTS = $(C_FILES:%=BUILD/%.o) BUILD/autogenerated/shaders.c.o

CFLAGS += -D_POSIX_C_SOURCE=200809L
CFLAGS += -std=c99
CFLAGS += -Iautogenerated
CFLAGS += -Iinclude
CFLAGS += -Wall
CFLAGS += -g

CFLAGS += $(shell pkg-config --cflags x11)
CFLAGS += $(shell pkg-config --cflags gl)
CFLAGS += $(shell pkg-config --cflags glu)

LDFLAGS += -lm
LDFLAGS += $(shell pkg-config --libs x11)
LDFLAGS += $(shell pkg-config --libs gl)
LDFLAGS += $(shell pkg-config --libs glu)

all: directories segments

clean:
	rm -rf segments BUILD autogenerated/

directories:
	@mkdir -p BUILD/src
	@mkdir -p BUILD/autogenerated

BUILD/%.c.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

segments: $(AUTOGEN_FILES) $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@





$(AUTOGEN_FILES): $(GLSL_FILES) $(GLSLPROC)
	$(GLSLPROC) autogenerated/

GLSLPROC_SOURCE_FILES = \
	process-shaders-src/main.c

GLSLPROC_CFLAGS =
GLSLPROC_CFLAGS += -Wall
GLSLPROC_CFLAGS += -std=c99
GLSLPROC_CFLAGS += -I ../glsl-processor/include

$(GLSLPROC): $(GLSLPROC_SOURCE_FILES) $(shell find ../glsl-processor/src -name '*.c')
	$(CC) $(GLSLPROC_CFLAGS) -o $@ $^
