C_FILES = \
	src/segments/main.c \
	src/segments/memory.c \
	src/segments/gfx.c \
	src/segments/glx11.c \
	src/segments/window.c \
	src/segments/logging.c \

GLSL_FILES = $(wildcard glsl/*)

AUTOGEN_FILES = \
	autogenerated/shaders.h \
	autogenerated/shaders.c

OBJECTS = $(C_FILES:%=BUILD/%.o) BUILD/autogenerated/shaders.c.o

CFLAGS += -D_POSIX_C_SOURCE=200809L
CFLAGS += -std=c99
CFLAGS += -Iautogenerated
CFLAGS += -Iinclude
CFLAGS += -Wall
CFLAGS += -g

CFLAGS += $(shell pkg-config --cflags x11)
CFLAGS += $(shell pkg-config --cflags gl)
CFLAGS += $(shell pkg-config --cflags glu)

LDFLAGS += -lm
LDFLAGS += $(shell pkg-config --libs x11)
LDFLAGS += $(shell pkg-config --libs gl)
LDFLAGS += $(shell pkg-config --libs glu)

all: directories segments

clean:
	rm -rf segments BUILD autogenerated/

directories:
	@mkdir -p BUILD/src/segments
	@mkdir -p BUILD/src/process-shaders
	@mkdir -p BUILD/autogenerated

BUILD/%.c.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

segments: $(AUTOGEN_FILES) $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@





$(AUTOGEN_FILES): process-shaders $(GLSL_FILES)
	./process-shaders autogenerated/

GLSLPROCESSOR_REPO_DIR = ./glsl-processor

PROCESSSHADERS_SOURCE_FILES = \
	$(wildcard src/process-shaders/*.c) \
	$(wildcard $(GLSLPROCESSOR_REPO_DIR)/src/*.c)

PROCESSSHADERS_CFLAGS =
PROCESSSHADERS_CFLAGS += -g
PROCESSSHADERS_CFLAGS += -Wall
PROCESSSHADERS_CFLAGS += -std=c99
PROCESSSHADERS_CFLAGS += -I $(GLSLPROCESSOR_REPO_DIR)/include

process-shaders: $(PROCESSSHADERS_SOURCE_FILES)
	$(CC) $(PROCESSSHADERS_CFLAGS) -o $@ $^
