#include <glsl-processor/builder.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

// defined in gen.c
extern void write_c_interface(struct GP_Ctx *ctx, const char *autogenDirpath);

static void fatal_f(const char *fmt, ...)
{
        va_list ap;
        va_start(ap, fmt);
        fprintf(stderr, "FATAL ERROR: ");
        vfprintf(stderr, fmt, ap);
        exit(1);
}

static void add_file(struct GP_Builder *sp, const char *fileID)
{
        const char *filepath = fileID; // might need better flexibility here

        FILE *f = fopen(filepath, "rb");
        if (f == NULL)
                fatal_f("Failed to open shader file '%s'", filepath);
        fseek(f, 0, SEEK_END);
        long size = ftell(f);
        char *data;
        data = malloc(size + 1);
        if (data == NULL)
                fatal_f("OOM!");
        fseek(f, 0, SEEK_SET);
        size_t nread = fread(data, 1, size + 1, f);
        if (nread != size)
                fatal_f("Expected to read %d bytes from '%s', but got %d",
                        size, filepath, nread);
        if (ferror(f))
                fatal_f("I/O error while reading from '%s'", filepath);
        fclose(f);
        gp_builder_create_file(sp, fileID, data, size);
}

static void add_shader_and_file(struct GP_Builder *sp, const char *shaderID, const char *fileID, int shadertypeKind)
{
        add_file(sp, fileID);
        gp_builder_create_shader(sp, shaderID, fileID, shadertypeKind);
}

int main(void)
{
        struct GP_Builder builder = {0};

        // Shader <-> Files is not a 1:1 relation
        add_file(&builder, "glsl/math.inc");

#define VERT(name) add_shader_and_file(&builder, name "_vert", "glsl/" name ".vert", GP_SHADERTYPE_VERTEX)
#define FRAG(name) add_shader_and_file(&builder, name "_frag", "glsl/" name ".frag", GP_SHADERTYPE_FRAGMENT)
        VERT("line");
        FRAG("line");
        VERT("circle");
        FRAG("circle");
        VERT("arc");
        FRAG("arc");
        VERT("v3");
        FRAG("v3");
#undef VERT
#undef FRAG

        gp_builder_create_program(&builder, "line");
        gp_builder_create_program(&builder, "circle");
        gp_builder_create_program(&builder, "arc");
        gp_builder_create_program(&builder, "v3");

        gp_builder_create_link(&builder, "line", "line_vert");
        gp_builder_create_link(&builder, "line", "line_frag");
        gp_builder_create_link(&builder, "circle", "circle_vert");
        gp_builder_create_link(&builder, "circle", "circle_frag");
        gp_builder_create_link(&builder, "arc", "arc_vert");
        gp_builder_create_link(&builder, "arc", "arc_frag");
        gp_builder_create_link(&builder, "v3", "v3_vert");
        gp_builder_create_link(&builder, "v3", "v3_frag");

        gp_builder_process(&builder);

        struct GP_Ctx ctx = {0};
        gp_builder_to_ctx(&builder, &ctx);
        gp_parse(&ctx);
        write_c_interface(&ctx, "autogenerated/");
        gp_teardown(&ctx);
        gp_builder_teardown(&builder);

        return 0;
}
